name: validate
on:
  push:
    branches:
    - main
    paths:
    - 'src/**'
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: validate
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: yaml validate
      run: python .github/test.py
