name: validate
on:
  push:
    branches:
    - main
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: validate
      run: |
        import yaml
        with open ('test.yaml','r') as file:
          yaml_content=yaml.safe_load(file)
          data=yaml_content['values']
          for key, value in data.items()
            print(f'{key}: {value}')
